version: '3.8'

services:
  cf-hero:
    build:
      context: .
      dockerfile: Dockerfile
    image: cf-hero:latest
    restart: unless-stopped
    
    # 环境变量
    environment:
      - TZ=Asia/Shanghai
    
    # 挂载示例文件
    volumes:
      - ./examples:/home/cfhero/examples
    
    # 启动时自动运行示例扫描，然后保持容器运行
    command: ["sh", "-c", "./cf-hero -f domains.txt && tail -f /dev/null"] 