version: '3.8'

services:
  cf-hero:
    build:
      context: .
      dockerfile: Dockerfile
    image: cf-hero:latest
    restart: unless-stopped
    
    # 环境变量
    environment:
      - TZ=Asia/Shanghai
    
    # 保持容器运行以便执行命令
    command: ["tail", "-f", "/dev/null"] 